### ISSUE TITLE
Recheck get_cost function

### ISSUE THREAD

**Issue by hnnam0906** [sair-lab/iMTSP#2]
Hi @gyf23205, @wang-chen, 

Could you explain why in the iMTSP/policy.py/get_cost function, you don't append the depot at the end of sub_tours?
If you don't add it, are their costs and the corresponding subtour_max_lengths correct? 

https://github.com/sair-lab/iMTSP/blob/83bad7b23d8afdd6520238c34a03a6e411240535/policy.py#L101

![image](https://github.com/user-attachments/assets/ff625c97-048e-4e99-83cb-dcbe25f2bde6)

Thanks

**Comment by gyf23205** [comment]
Hi,
Sorry about the confusion. Here, the "sub_tours" are really "allocations". You can see I just iterate through the "action" (which assigns every city to an agent) without reordering the cities. The actual sub-tours are given below with "solve" or "my_solve" functions, where the classic solver treats the first city in each allocation as the depot.

**Comment by hnnam0906** [comment]
Hi @gyf23205,
Thanks for your quick response.

I have 2 below questions, hope you can review and answer them.
1. Does the solve function use the Euclidean2D distance? I try not to use the ortools lib but add the depot at the end of the sub tours and calculate the distance directly in a naive way as below. Then i retrain and make a test, however, the cost is different and higher (normally more than 2-time higher) which is compared to the result from solve func.  

![image](https://github.com/user-attachments/assets/7a6947a6-30e1-4b31-b610-dde2953e7f2d)

2. How can i test for any arbitrary number of nodes and agents? i.e. Can i use a trained model for 50 nodes and 5 agents to test for bigger numbers, like 100 nodes or with 8 agents?

Thanks

**Comment by gyf23205** [comment]
Hi,
For the first comment, I'm not sure what your question is. The result is expected since the naive way of computing route length won't give the allocation network quality supervision. For the second question, the current structure already supports generalization to different numbers of cities. You don't need to do anything but generate the data. However, you will need to train another model if you change the number of agents.

**Comment by hnnam0906** [comment]
Hi @gyf23205,
Regarding the first question, I mean there is a difference between using the naive method and the solve function. It doesn't match the result and the cost from naive is often higher than the one from the solve function. The naive method calculates the closed route length beginning at a deport and ending at the same depot. Should it be the target for the mTSP problem? Which cost does the solve function calculate if it is not the route length?

For the second one, I mean if user inputs any numbers for the cities and agents, i.e. assume that we limit them in their ranges like 500 <= number of cities <=2000, 2 <= number of agents <= 10, what model should i use to evaluate? 
If i train every pair of city and agent, it needs (2000-500+1) * (10-2+1) =  13509 cases to train. It is nearly impossible for me to train such a kind of cases.

Thanks

**Comment by gyf23205** [comment]
Hi,
For the first question. No, the result of the "naive" method is not the target of the solver. For routing problems, the **ORDER** of visiting is **curtial**. The solver tries to find the near-optimal order of visiting the allocated cities and return the length of that route.

For the second question, again, you don't need to retrain anything if you just want to change the number of cities in your problem. But, you will need to train a different model if you want to change the number of agents. In your example, you will need to train in total 9 = 10 -2 + 1 models.

**Comment by hnnam0906** [comment]
Hi @gyf23205,
Thanks for your enthusiasm. Got it, i will investigate more deeply, following your instructions.
